server:  port: 80  servlet:    context-path: /api
 
spring:
  profiles:
    active: devlimit:  pageSize: 2  description: 每页两条信息2条      
#mybatis:  
  #mapperLocations: classpath*:com/example/demo/mapper/*.xmllogging:  level:     com.example.demo.mapper: debug         #PageHelper#pagehelper:  #helper-dialect: mysql  #reasonable: true  #offsetAsPageNum: true  #rowBoundsWithCount: true  #support-methods-arguments: true  #params: count=countSql  